// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aninja_character_service.Data;

#nullable disable

namespace aninja_character_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220327115606_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("aninja_character_service.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<string>("TranslatedTitle")
                        .HasColumnType("text")
                        .HasColumnName("translated_title");

                    b.HasKey("Id");

                    b.ToTable("animes", (string)null);
                });

            modelBuilder.Entity("aninja_character_service.Models.AnimeCharacter", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("anime_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.HasKey("AnimeId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("anime_character", (string)null);
                });

            modelBuilder.Entity("aninja_character_service.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("OriginalName")
                        .HasColumnType("text")
                        .HasColumnName("original_name");

                    b.Property<string>("TranslatedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translated_name");

                    b.Property<string>("VoiceActor")
                        .HasColumnType("text")
                        .HasColumnName("voice_actor");

                    b.Property<string>("VoiceActorImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("voice_actor_image_url");

                    b.HasKey("Id");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("aninja_character_service.Models.AnimeCharacter", b =>
                {
                    b.HasOne("aninja_character_service.Models.Anime", "Anime")
                        .WithMany("Characters")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aninja_character_service.Models.Character", "Character")
                        .WithMany("Animes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("aninja_character_service.Models.Anime", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("aninja_character_service.Models.Character", b =>
                {
                    b.Navigation("Animes");
                });
#pragma warning restore 612, 618
        }
    }
}
